modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="bedrockutils"
version="0.3"
displayName="BedrockUtils"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MinoCraft72"

[[dependencies.bedrockutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedrockutils]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.bedrockutils]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bedrockutils]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

